### ISSUE TITLE
Merb.thor broken with rubygems-1.3.2

### ISSUE THREAD

**Issue by adelcambre** [wycats/merb#2]
<pre>
andy@hiro:...project[master*]➤ thor merb:gem:install
Beginning transaction
wrong number of arguments (4 for 3)
/Library/Ruby/Site/1.8/rubygems/dependency_installer.rb:99:in `fetch'
/Library/Ruby/Site/1.8/rubygems/dependency_installer.rb:99:in `old_fg'
/Users/andy/projects/project/tasks/merb.thor/gem_ext.rb:75:in `find_gems_with_sources'
/Library/Ruby/Site/1.8/rubygems/dependency_installer.rb:192:in `find_spec_by_name_and_version'
/Library/Ruby/Site/1.8/rubygems/dependency_installer.rb:213:in `install'
/Users/andy/projects/project/tasks/merb.thor/ops.rb:82:in `_install'
/Users/andy/projects/project/tasks/merb.thor/main.thor:123:in `install'
/Users/andy/projects/project/tasks/merb.thor/ops.rb:40:in `rescue_failures'
/Users/andy/projects/project/tasks/merb.thor/main.thor:121:in `install'
/Users/andy/projects/project/tasks/merb.thor/main.thor:115:in `each'
/Users/andy/projects/project/tasks/merb.thor/main.thor:115:in `install'
/Library/Ruby/Gems/1.8/gems/thor-0.9.9/lib/thor/task.rb:27:in `send'
/Library/Ruby/Gems/1.8/gems/thor-0.9.9/lib/thor/task.rb:27:in `run'
/Library/Ruby/Gems/1.8/gems/thor-0.9.9/lib/thor/task.rb:20:in `parse'
/Library/Ruby/Gems/1.8/gems/thor-0.9.9/lib/thor/runner.rb:155:in `method_missing'
/Library/Ruby/Gems/1.8/gems/thor-0.9.9/lib/thor/task.rb:27:in `send'
/Library/Ruby/Gems/1.8/gems/thor-0.9.9/lib/thor/task.rb:27:in `run'
/Library/Ruby/Gems/1.8/gems/thor-0.9.9/lib/thor/task.rb:20:in `parse'
/Library/Ruby/Gems/1.8/gems/thor-0.9.9/lib/thor.rb:78:in `start'
/Library/Ruby/Gems/1.8/gems/thor-0.9.9/bin/thor:7
/usr/bin/thor:19:in `load'
/usr/bin/thor:19
Rolling back transaction
</pre>

**Comment by ghost** [comment]
change line 81 of gem_ext.rb to

>   def fetch(dependency, all = false, matching_platform = true, prerelease = false)

and line 97 to

> old_fetch(dependency, all, matching_platform, prerelease)

**Comment by jonuts** [comment]
good stuff jproxx

**Comment by motdotla** [comment]
ditto
