### ISSUE TITLE
Merb::Parse.multipart fails on binary uploads (patch included)

### ISSUE THREAD

**Issue by ujifgc** [wycats/merb#5]
These patches eliminate error "invalid byte sequence in UTF-8" raised by uploading binaries.
file merb-core/dispatch/request_parsers.rb
52: buf = ""
insert buf.force_encoding('BINARY')

66: body = ''
insert body.force_encoding('BINARY')

**Comment by ujifgc** [comment]
Crappy patch. Must set 'BINARY' also to c = input.read(read_size). Is there a nicer workaround?

**Comment by ujifgc** [comment]
Uh great...   Just set Encoding.default_external = 'BINARY'

**Comment by sintaxi** [comment]
thanks ujifgc this information is helpful.
